/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;

import Controle.CConta;
import Modelo.MConta;
import javax.swing.JOptionPane;

public class IConta extends javax.swing.JFrame {

    MConta modConta = new MConta();
    CConta conta = new CConta();
    String usuario = TelaLogin.getUsuario();
    private boolean isEdit;
    private Integer codCon;

    public IConta() {
        initComponents();
        cxbAtiva.setEnabled(false);
        txtDescricao.requestFocus();
    }

    public IConta(MConta conta) {
        initComponents();
        txtDescricao.setText(conta.getDescricao());
        cxbAtiva.setSelected(conta.getAtivo() == 1);
        txtSaldo.setText(Float.toString(conta.getSaldo()));
        codCon = conta.getCodcon();
        isEdit = true;
        txtDescricao.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        cxbAtiva = new javax.swing.JCheckBox();
        btSalvar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        txtSaldo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conta");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(310, 315));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbDescricao.setText("*Descrição:");
        jPanel1.add(lbDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 79, -1));

        txtDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDescricao.setBorder(null);
        jPanel1.add(txtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 290, -1));

        cxbAtiva.setBackground(new java.awt.Color(255, 255, 255));
        cxbAtiva.setSelected(true);
        cxbAtiva.setText("Ativa");
        jPanel1.add(cxbAtiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 65, -1));

        btSalvar.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btSalvar.setText("SALVAR");
        btSalvar.setAutoscrolls(true);
        btSalvar.setBorder(null);
        btSalvar.setContentAreaFilled(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 80, 37));

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ic_clear_black_24dp_1x.png"))); // NOI18N
        btSair.setAutoscrolls(true);
        btSair.setContentAreaFilled(false);
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        jPanel1.add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 30, 38));

        txtSaldo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtSaldo.setBorder(null);
        txtSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoActionPerformed(evt);
            }
        });
        jPanel1.add(txtSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 180, 30));

        jLabel1.setText("Saldo Inicial:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 290, -1));

        jPanel2.setBackground(new java.awt.Color(162, 88, 203));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon#3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 100));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 220, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("R$");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(310, 340));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (conta.verificaSeNumerico(txtSaldo.getText())) {
            modConta.setDescricao(txtDescricao.getText());
            modConta.setSaldo(txtSaldo.getText());
            modConta.setAtivo(cxbAtiva.isSelected());
            modConta.setUsuario(usuario);
            if (conta.validaCampos(modConta, isEdit)) {
                if (!isEdit) {
                    conta.Salvar(modConta);
                } else {
                    modConta.setCodcon(codCon);
                    conta.Editar(modConta);
                }
                Conta telaConta = Conta.getInstance();
                telaConta.limpaTabela();
                telaConta.preencheTabela("select * from CONTA  natural join USUARIO where CODUSU = " + usuario + " order by CODCON");
                telaConta.setVisible(true);
                dispose();
            } else {
                txtDescricao.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Valor digitado não numérico!");
            txtSaldo.requestFocus();
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        Categoria telaCategoria = Categoria.getInstance();
        telaCategoria.setEnabled(true);
        setVisible(false);
    }//GEN-LAST:event_btSairActionPerformed

    private void txtSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSalvar;
    private javax.swing.JCheckBox cxbAtiva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
