/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;

import Controle.CTransacoes;
import Modelo.MComboBox;
import Modelo.MTransacoes;
import java.awt.ComponentOrientation;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author renat
 */
public class ITransacao extends javax.swing.JFrame {

    MTransacoes modTransac = new MTransacoes();
    CTransacoes Transac = new CTransacoes();
    String usuario = TelaLogin.getUsuario();
    private boolean isEdit;
    private Integer codTra;
    private Integer codTraDest;

    public ITransacao() {
        initComponents();
        povoaCombos();
        dtData.setDate(new java.util.Date());
        t_dtData.setDate(new java.util.Date());
    }

    public ITransacao(MTransacoes transacoes) {
        initComponents();
        povoaCombos();
        if (!"T".equals(transacoes.getTipo())) {
            jTabbedPane.setSelectedIndex(0);
            jTabbedPane.setEnabledAt(1, false);
            txtValor.setText(Float.toString(transacoes.getValor()));
            txtDescricao.setText(transacoes.getDescricao());
            dtData.setDate(transacoes.getData());
            cbConta.setSelectedItem(transacoes.getConta());
            cbCategoria.setSelectedItem(transacoes.getCateg());
            cxbConsolidada.setSelected(transacoes.getPago() == 1);
            switch (transacoes.getTipo()) {
                case "D":
                    cbTipo.setSelectedIndex(0);
                    break;
                case "R":
                    cbTipo.setSelectedIndex(1);
                    break;
            }
            spParcelar.setValue(transacoes.getLembrete());
            pnNota.setText(transacoes.getNota());
        } else {
            jTabbedPane.setSelectedIndex(1);
            jTabbedPane.setEnabledAt(0, false);
            t_txtValor.setText(Float.toString(transacoes.getValor()));
            t_dtData.setDate(transacoes.getData());
            t_cbConta.setSelectedItem(transacoes.getConta());
            t_cbContaDest.setSelectedItem(transacoes.getContaDest());
            t_cxbConsolidada.setSelected(transacoes.getPago() == 1);
            t_spLembrete.setValue(transacoes.getLembrete());
            t_pnNota.setText(transacoes.getNota());
            codTraDest = transacoes.getCodtraDest();
        }
        codTra = transacoes.getCodtra();
        isEdit = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btSalvarNovo = new javax.swing.JButton();
        btSalvarNovo1 = new javax.swing.JButton();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lbValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        dtData = new com.toedter.calendar.JDateChooser();
        lbData = new javax.swing.JLabel();
        lbDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        lbConta = new javax.swing.JLabel();
        cbConta = new javax.swing.JComboBox<>();
        lbCategoria = new javax.swing.JLabel();
        cbCategoria = new javax.swing.JComboBox<>();
        lbCategoria1 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        cxbConsolidada = new javax.swing.JCheckBox();
        spParcelar = new com.toedter.components.JSpinField();
        lbLembrete = new javax.swing.JLabel();
        lbNota = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnNota = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        cxbParcelar = new javax.swing.JCheckBox();
        spLembrete1 = new com.toedter.components.JSpinField();
        jPanel3 = new javax.swing.JPanel();
        t_lbValor = new javax.swing.JLabel();
        t_txtValor = new javax.swing.JTextField();
        t_lbData = new javax.swing.JLabel();
        t_cbConta = new javax.swing.JComboBox<>();
        t_lbConta = new javax.swing.JLabel();
        t_cxbConsolidada = new javax.swing.JCheckBox();
        t_spLembrete = new com.toedter.components.JSpinField();
        t_lbLembrete = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_pnNota = new javax.swing.JTextPane();
        t_lbNota = new javax.swing.JLabel();
        t_cbContaDest = new javax.swing.JComboBox<>();
        t_lbContaDest = new javax.swing.JLabel();
        t_dtData = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jMenu4.setText("Arquivo");

        jMenu2.setText("Usuário");
        jMenu4.add(jMenu2);

        jMenu9.setText("Conta");
        jMenu4.add(jMenu9);

        jMenu1.setText("Categoria");
        jMenu4.add(jMenu1);

        jMenu10.setText("Transação");
        jMenu4.add(jMenu10);

        jMenuBar2.add(jMenu4);

        jMenu3.setText("Editar");

        jMenu6.setText("Novo");
        jMenu3.add(jMenu6);

        jMenu7.setText("Alterar");
        jMenu3.add(jMenu7);

        jMenu8.setText("Excluir");
        jMenu3.add(jMenu8);

        jMenuBar2.add(jMenu3);

        jMenu11.setText("Relatório");

        jMenu13.setText("Categoria");
        jMenu11.add(jMenu13);

        jMenu12.setText("Conta");
        jMenu11.add(jMenu12);

        jMenu14.setText("Usuário");
        jMenu11.add(jMenu14);

        jMenu15.setText("Receita");
        jMenu11.add(jMenu15);

        jMenu17.setText("Transferência");
        jMenu11.add(jMenu17);

        jMenu16.setText("Despesa");
        jMenu11.add(jMenu16);

        jMenuBar2.add(jMenu11);

        jMenu5.setText("Ajuda");

        jMenu18.setText("Sobre");
        jMenu5.add(jMenu18);

        jMenuBar2.add(jMenu5);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Conta");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nova Transação");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btSalvarNovo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btSalvarNovo.setText("SALVAR");
        btSalvarNovo.setAutoscrolls(true);
        btSalvarNovo.setBorder(null);
        btSalvarNovo.setContentAreaFilled(false);
        btSalvarNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarNovoActionPerformed(evt);
            }
        });
        jPanel1.add(btSalvarNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 82, 40));

        btSalvarNovo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ic_clear_black_24dp_1x.png"))); // NOI18N
        btSalvarNovo1.setAutoscrolls(true);
        btSalvarNovo1.setContentAreaFilled(false);
        btSalvarNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarNovo1ActionPerformed(evt);
            }
        });
        jPanel1.add(btSalvarNovo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 40, 40));

        jTabbedPane.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbValor.setText("*Valor:");
        jPanel2.add(lbValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 48, -1));

        txtValor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtValor.setBorder(null);
        jPanel2.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 150, 210, 30));
        jPanel2.add(dtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 126, -1));

        lbData.setText("*Data:");
        jPanel2.add(lbData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 44, -1));

        lbDescricao.setText("*Descrição:");
        jPanel2.add(lbDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 79, -1));

        txtDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDescricao.setBorder(null);
        jPanel2.add(txtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 226, -1));

        lbConta.setText("*Conta:");
        jPanel2.add(lbConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 66, -1));

        cbConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cbConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 176, -1));

        lbCategoria.setText("*Categoria: ");
        jPanel2.add(lbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 70, 90, -1));

        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 90, 176, -1));

        lbCategoria1.setText("*Tipo:");
        jPanel2.add(lbCategoria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 90, -1));

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Despesa", "Receita" }));
        jPanel2.add(cbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 31, 131, -1));

        cxbConsolidada.setBackground(new java.awt.Color(255, 255, 255));
        cxbConsolidada.setSelected(true);
        cxbConsolidada.setText("Consolidada");
        jPanel2.add(cxbConsolidada, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 94, -1));

        spParcelar.setEnabled(false);
        spParcelar.setMinimum(0);
        jPanel2.add(spParcelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 40, -1));

        lbLembrete.setText("Lembrete:");
        jPanel2.add(lbLembrete, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 69, -1));

        lbNota.setText("Nota:");
        jPanel2.add(lbNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 62, -1));

        jScrollPane1.setViewportView(pnNota);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 372, 55));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("R$");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 226, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 245, -1));

        cxbParcelar.setBackground(new java.awt.Color(255, 255, 255));
        cxbParcelar.setText("Parcelar em:");
        cxbParcelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxbParcelarActionPerformed(evt);
            }
        });
        jPanel2.add(cxbParcelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        spLembrete1.setMinimum(0);
        jPanel2.add(spLembrete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 62, -1));

        jTabbedPane.addTab("Despesa/Receita", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_lbValor.setText("*Valor:");
        jPanel3.add(t_lbValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 48, -1));

        t_txtValor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        t_txtValor.setBorder(null);
        jPanel3.add(t_txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 90, 220, 30));

        t_lbData.setText("*Data:");
        jPanel3.add(t_lbData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 44, -1));

        t_cbConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(t_cbConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 176, -1));

        t_lbConta.setText("*Conta Origem:");
        jPanel3.add(t_lbConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 109, -1));

        t_cxbConsolidada.setBackground(new java.awt.Color(255, 255, 255));
        t_cxbConsolidada.setSelected(true);
        t_cxbConsolidada.setText("Consolidada");
        jPanel3.add(t_cxbConsolidada, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 94, -1));
        jPanel3.add(t_spLembrete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 215, 62, -1));

        t_lbLembrete.setText("Lembrete:");
        jPanel3.add(t_lbLembrete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 195, 69, -1));

        jScrollPane2.setViewportView(t_pnNota);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 375, 65));

        t_lbNota.setText("Nota:");
        jPanel3.add(t_lbNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 62, -1));

        t_cbContaDest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(t_cbContaDest, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 176, -1));

        t_lbContaDest.setText("*Conta Destino:");
        jPanel3.add(t_lbContaDest, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 107, -1));
        jPanel3.add(t_dtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 126, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("R$");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 254, -1));

        jTabbedPane.addTab("Transferência", jPanel3);

        jPanel1.add(jTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 79, 400, 380));

        jPanel4.setBackground(new java.awt.Color(255, 99, 66));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon#1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(37, 37, 37))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 510));

        setSize(new java.awt.Dimension(400, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarNovoActionPerformed
        double valor;
        if (jTabbedPane.getSelectedIndex() == 0) {
            if (Transac.verificaSeNumerico(txtValor.getText())) {
                modTransac.setValor(txtValor.getText());
                modTransac.setDescricao(txtDescricao.getText());
                modTransac.setData(dtData.getDate());
                modTransac.setConta(cbConta.getSelectedItem().toString());
                modTransac.setCateg(cbCategoria.getSelectedItem().toString());
                modTransac.setPago(cxbConsolidada.isSelected());
                modTransac.setLembrete(spParcelar.getValue());
                modTransac.setNota(pnNota.getText());
                modTransac.setUsuario(usuario);
                switch (cbTipo.getSelectedIndex()) {
                    case 0:
                        modTransac.setTipo("D");
                        break;
                    case 1:
                        modTransac.setTipo("R");
                        break;
                }

                if (Transac.validaCampos(modTransac)) {
                    if (!isEdit) {
                        if (cxbParcelar.isSelected() && (spParcelar.getValue() > 0)) {
                            modTransac.setValor(String.valueOf(Float.parseFloat(txtValor.getText())/spParcelar.getValue()));
                            for (int i = 0; i < spParcelar.getValue(); i++) {
                                Transac.Salvar(modTransac);
                            }
                        } else {
                            Transac.Salvar(modTransac);
                        }
                    } else {
                        modTransac.setCodtra(codTra);
                        Transac.Editar(modTransac);
                    }
                    Transacoes telaTransacoes = Transacoes.getInstance();
                    telaTransacoes.limpaTabela();
                    telaTransacoes.preencheTabela("select * from TRANSACAO T left join CATEGORIA USING(CODCAT) left join CONTA using (CODCON) join USUARIO U on U.CODUSU = T.CODUSU where T.CODUSU = " + usuario + " order by CODTRA, DATA");
                    telaTransacoes.setVisible(true);
                    dispose();
                } else {
                    txtDescricao.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Valor digitado não numérico!");
                txtValor.requestFocus();
            }
        } else {
            if (Transac.verificaSeNumerico(t_txtValor.getText())) {
                modTransac.setValor(t_txtValor.getText());
                modTransac.setData(t_dtData.getDate());
                modTransac.setConta(t_cbConta.getSelectedItem().toString());
                modTransac.setContaDest(t_cbContaDest.getSelectedItem().toString());
                modTransac.setPago(t_cxbConsolidada.isSelected());
                modTransac.setLembrete(t_spLembrete.getValue());
                modTransac.setNota(t_pnNota.getText());
                modTransac.setUsuario(usuario);
                modTransac.setTipo("T");

                if (Transac.validaCampos(modTransac)) {
                    if (!isEdit) {
                        Transac.Salvar(modTransac);
                    } else {
                        modTransac.setCodtra(codTra);
                        modTransac.setCodtraDest(codTraDest);
                        Transac.Editar(modTransac);
                    }
                    Transacoes telaTransacoes = Transacoes.getInstance();
                    telaTransacoes.limpaTabela();
                    telaTransacoes.preencheTabela("select * from TRANSACAO T left join CATEGORIA USING(CODCAT) left join CONTA using (CODCON) join USUARIO U on U.CODUSU = T.CODUSU where T.CODUSU = " + usuario + " order by CODTRA, DATA");
                    telaTransacoes.setVisible(true);
                    dispose();
                } else {
                    t_cbConta.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Valor digitado não numérico!");
                t_txtValor.requestFocus();
            }
        }
    }//GEN-LAST:event_btSalvarNovoActionPerformed

    private void btSalvarNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarNovo1ActionPerformed
        Transacoes telaTransacoes = Transacoes.getInstance();
        telaTransacoes.setEnabled(true);
        setVisible(false);
    }//GEN-LAST:event_btSalvarNovo1ActionPerformed

    private void cxbParcelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxbParcelarActionPerformed
        spParcelar.setEnabled(cxbParcelar.isSelected());
    }//GEN-LAST:event_cxbParcelarActionPerformed

    private void povoaCombos() {
        MComboBox mConta = new MComboBox(Transac.buscaContas(usuario));
        MComboBox mContaDesp = new MComboBox(Transac.buscaContas(usuario));
        MComboBox mCategoria = new MComboBox(Transac.buscaCategorias(usuario));
        cbConta.setModel(mConta);
        cbCategoria.setModel(mCategoria);
        t_cbConta.setModel(mConta);
        t_cbContaDest.setModel(mContaDesp);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ITransacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ITransacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ITransacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ITransacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ITransacao().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalvarNovo;
    private javax.swing.JButton btSalvarNovo1;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JComboBox<String> cbConta;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JCheckBox cxbConsolidada;
    private javax.swing.JCheckBox cxbParcelar;
    private com.toedter.calendar.JDateChooser dtData;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbCategoria1;
    private javax.swing.JLabel lbConta;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JLabel lbLembrete;
    private javax.swing.JLabel lbNota;
    private javax.swing.JLabel lbValor;
    private javax.swing.JTextPane pnNota;
    private com.toedter.components.JSpinField spLembrete1;
    private com.toedter.components.JSpinField spParcelar;
    private javax.swing.JComboBox<String> t_cbConta;
    private javax.swing.JComboBox<String> t_cbContaDest;
    private javax.swing.JCheckBox t_cxbConsolidada;
    private com.toedter.calendar.JDateChooser t_dtData;
    private javax.swing.JLabel t_lbConta;
    private javax.swing.JLabel t_lbContaDest;
    private javax.swing.JLabel t_lbData;
    private javax.swing.JLabel t_lbLembrete;
    private javax.swing.JLabel t_lbNota;
    private javax.swing.JLabel t_lbValor;
    private javax.swing.JTextPane t_pnNota;
    private com.toedter.components.JSpinField t_spLembrete;
    private javax.swing.JTextField t_txtValor;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
