package Visão;

import Controle.CConexaoBD;

public class Principal extends javax.swing.JFrame {
    
    CConexaoBD conexao = new CConexaoBD();
    
    private static Principal instancia;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        btConfiguracoes.setEnabled(false);
        conexao.conecta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btNovaTransacao = new javax.swing.JButton();
        jPanelMenuPrincipal = new javax.swing.JPanel();
        btTransacoes = new javax.swing.JButton();
        btContas = new javax.swing.JButton();
        btCategoria = new javax.swing.JButton();
        btConfiguracoes = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu19 = new javax.swing.JMenu();
        btMenuTransacoes = new javax.swing.JRadioButtonMenuItem();
        btMenuConta = new javax.swing.JRadioButtonMenuItem();
        btMenuCategoria = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem15 = new javax.swing.JRadioButtonMenuItem();
        btMenuSair = new javax.swing.JRadioButtonMenuItem();
        jMenu28 = new javax.swing.JMenu();
        jRadioButtonMenuItem8 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem9 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem10 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem11 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem12 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem13 = new javax.swing.JRadioButtonMenuItem();
        jMenu35 = new javax.swing.JMenu();
        jRadioButtonMenuItem14 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Easy Personal Finances Garrett");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btNovaTransacao.setText("+ Nova Transação");
        btNovaTransacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovaTransacaoActionPerformed(evt);
            }
        });
        jPanel1.add(btNovaTransacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 610, 140, 40));

        jPanelMenuPrincipal.setBackground(new java.awt.Color(234, 237, 239));
        jPanelMenuPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btTransacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/analytics.png"))); // NOI18N
        btTransacoes.setBorder(null);
        btTransacoes.setContentAreaFilled(false);
        btTransacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTransacoesActionPerformed(evt);
            }
        });
        jPanelMenuPrincipal.add(btTransacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 2, -1, 110));

        btContas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/money-bag.png"))); // NOI18N
        btContas.setBorder(null);
        btContas.setContentAreaFilled(false);
        btContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContasActionPerformed(evt);
            }
        });
        jPanelMenuPrincipal.add(btContas, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 2, -1, 110));

        btCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/books.png"))); // NOI18N
        btCategoria.setBorder(null);
        btCategoria.setContentAreaFilled(false);
        btCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCategoriaActionPerformed(evt);
            }
        });
        jPanelMenuPrincipal.add(btCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 2, -1, 110));

        btConfiguracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/wrench.png"))); // NOI18N
        btConfiguracoes.setToolTipText("");
        btConfiguracoes.setBorder(null);
        btConfiguracoes.setContentAreaFilled(false);
        btConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfiguracoesActionPerformed(evt);
            }
        });
        jPanelMenuPrincipal.add(btConfiguracoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 2, -1, 110));

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/open-door.png"))); // NOI18N
        btSair.setBorder(null);
        btSair.setContentAreaFilled(false);
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        jPanelMenuPrincipal.add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 2, -1, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/onlinelogomaker-061817-1509-5100.png"))); // NOI18N
        jPanelMenuPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(767, 34, -1, -1));

        jLabel3.setText("Configurações");
        jPanelMenuPrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 107, -1, -1));

        jLabel4.setText("Categorias");
        jPanelMenuPrincipal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 107, -1, -1));

        jLabel5.setText("Sair");
        jPanelMenuPrincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 107, -1, -1));

        jLabel6.setText("Contas");
        jPanelMenuPrincipal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 107, -1, -1));

        jLabel7.setText("Transações");
        jPanelMenuPrincipal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 107, -1, -1));

        jPanel1.add(jPanelMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 125));

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Icon made by Vectors Market from www.flaticon.com ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 650, 1100, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 86)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("00,00");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1100, 130));

        jMenu19.setText("Arquivo");

        btMenuTransacoes.setSelected(true);
        btMenuTransacoes.setText("Transações");
        btMenuTransacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTransacoesActionPerformed(evt);
            }
        });
        jMenu19.add(btMenuTransacoes);

        btMenuConta.setSelected(true);
        btMenuConta.setText("Conta");
        btMenuConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContasActionPerformed(evt);
            }
        });
        jMenu19.add(btMenuConta);

        btMenuCategoria.setSelected(true);
        btMenuCategoria.setText("Categoria");
        btMenuCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCategoriaActionPerformed(evt);
            }
        });
        jMenu19.add(btMenuCategoria);

        jRadioButtonMenuItem15.setSelected(true);
        jRadioButtonMenuItem15.setText("Configurações");
        jRadioButtonMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfiguracoesActionPerformed(evt);
            }
        });
        jMenu19.add(jRadioButtonMenuItem15);

        btMenuSair.setSelected(true);
        btMenuSair.setText("Sair");
        btMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        jMenu19.add(btMenuSair);

        jMenuBar3.add(jMenu19);

        jMenu28.setText("Relatório");

        jRadioButtonMenuItem8.setSelected(true);
        jRadioButtonMenuItem8.setText("Usuários");
        jRadioButtonMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem8ActionPerformed(evt);
            }
        });
        jMenu28.add(jRadioButtonMenuItem8);

        jRadioButtonMenuItem9.setSelected(true);
        jRadioButtonMenuItem9.setText("Categorias");
        jRadioButtonMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem9ActionPerformed(evt);
            }
        });
        jMenu28.add(jRadioButtonMenuItem9);

        jRadioButtonMenuItem10.setSelected(true);
        jRadioButtonMenuItem10.setText("Transações");
        jRadioButtonMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem10ActionPerformed(evt);
            }
        });
        jMenu28.add(jRadioButtonMenuItem10);

        jRadioButtonMenuItem11.setSelected(true);
        jRadioButtonMenuItem11.setText("Receitas");
        jRadioButtonMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem11ActionPerformed(evt);
            }
        });
        jMenu28.add(jRadioButtonMenuItem11);

        jRadioButtonMenuItem12.setSelected(true);
        jRadioButtonMenuItem12.setText("Despesas");
        jRadioButtonMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem12ActionPerformed(evt);
            }
        });
        jMenu28.add(jRadioButtonMenuItem12);

        jRadioButtonMenuItem13.setSelected(true);
        jRadioButtonMenuItem13.setText("Transferências");
        jRadioButtonMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem13ActionPerformed(evt);
            }
        });
        jMenu28.add(jRadioButtonMenuItem13);

        jMenuBar3.add(jMenu28);

        jMenu35.setText("Ajuda");

        jRadioButtonMenuItem14.setSelected(true);
        jRadioButtonMenuItem14.setText("Sobre");
        jRadioButtonMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem14ActionPerformed(evt);
            }
        });
        jMenu35.add(jRadioButtonMenuItem14);

        jMenuBar3.add(jMenu35);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1116, 723));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void btTransacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTransacoesActionPerformed
        Transacoes telaTransacoes = Transacoes.getInstance();
        this.setVisible(false);
        telaTransacoes.setVisible(true);
    }//GEN-LAST:event_btTransacoesActionPerformed

    private void btConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfiguracoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btConfiguracoesActionPerformed

    private void btContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContasActionPerformed
        Conta telaConta = Conta.getInstance();
        this.setVisible(false);
        telaConta.setVisible(true);
    }//GEN-LAST:event_btContasActionPerformed

    private void btNovaTransacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovaTransacaoActionPerformed
        ITransacao telaTransacao = new ITransacao();
        this.setEnabled(false);
        telaTransacao.setVisible(true);
    }//GEN-LAST:event_btNovaTransacaoActionPerformed

    private void jRadioButtonMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem8ActionPerformed

    }//GEN-LAST:event_jRadioButtonMenuItem8ActionPerformed

    private void jRadioButtonMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem9ActionPerformed

    }//GEN-LAST:event_jRadioButtonMenuItem9ActionPerformed

    private void jRadioButtonMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem10ActionPerformed

    }//GEN-LAST:event_jRadioButtonMenuItem10ActionPerformed

    private void jRadioButtonMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem11ActionPerformed

    }//GEN-LAST:event_jRadioButtonMenuItem11ActionPerformed

    private void jRadioButtonMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem12ActionPerformed

    }//GEN-LAST:event_jRadioButtonMenuItem12ActionPerformed

    private void jRadioButtonMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem13ActionPerformed

    }//GEN-LAST:event_jRadioButtonMenuItem13ActionPerformed

    private void jRadioButtonMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem14ActionPerformed

    }//GEN-LAST:event_jRadioButtonMenuItem14ActionPerformed

    private void btCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCategoriaActionPerformed
        Categoria telaCategoria = Categoria.getInstance();
        this.setVisible(false);
        telaCategoria.setVisible(true);
    }//GEN-LAST:event_btCategoriaActionPerformed
    
    public static Principal getInstance() { // MÉTODO QUE VERIFICA SE A INSTANCIA JÁ ESTÁ CRIADA (SINGLETON)
        if (instancia == null) {
            instancia = new Principal();
        }
        return instancia;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCategoria;
    private javax.swing.JButton btConfiguracoes;
    private javax.swing.JButton btContas;
    private javax.swing.JRadioButtonMenuItem btMenuCategoria;
    private javax.swing.JRadioButtonMenuItem btMenuConta;
    private javax.swing.JRadioButtonMenuItem btMenuSair;
    private javax.swing.JRadioButtonMenuItem btMenuTransacoes;
    private javax.swing.JButton btNovaTransacao;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btTransacoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu28;
    private javax.swing.JMenu jMenu35;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMenuPrincipal;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem10;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem11;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem12;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem13;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem14;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem15;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem8;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem9;
    // End of variables declaration//GEN-END:variables
}
