package Visão;

import Controle.CConexaoBD;
import Modelo.MTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

public class Principal extends javax.swing.JFrame {

    CConexaoBD conexao = new CConexaoBD();

    private static Principal instancia;
    String usuario = TelaLogin.getUsuario();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        System.setProperty("java.awt.headless", "true");
        preencheTabelaLembretes();
        preencheTabelaTransac();
        totalGasto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelMenuPrincipal = new javax.swing.JPanel();
        btTransacoes = new javax.swing.JButton();
        btContas = new javax.swing.JButton();
        btCategoria = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cxbSaldoAcumulado = new javax.swing.JCheckBox();
        jLabelTot = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTransac = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableLembrete = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu19 = new javax.swing.JMenu();
        btMenuTransacoes = new javax.swing.JRadioButtonMenuItem();
        btMenuConta = new javax.swing.JRadioButtonMenuItem();
        btMenuCategoria = new javax.swing.JRadioButtonMenuItem();
        btMenuSair = new javax.swing.JRadioButtonMenuItem();
        jMenu28 = new javax.swing.JMenu();
        jrbCategorias = new javax.swing.JRadioButtonMenuItem();
        jrbConta = new javax.swing.JRadioButtonMenuItem();
        jrbTransacoes = new javax.swing.JRadioButtonMenuItem();
        jrbReceitas = new javax.swing.JRadioButtonMenuItem();
        jrbDespesas = new javax.swing.JRadioButtonMenuItem();
        jrbTransferencias = new javax.swing.JRadioButtonMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jrbGrafReceita = new javax.swing.JRadioButtonMenuItem();
        jrbGrafDespesas = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jrbPReceitas = new javax.swing.JRadioButtonMenuItem();
        jrbPDespesas = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Easy Personal Finances Garrett");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMenuPrincipal.setBackground(new java.awt.Color(234, 237, 239));
        jPanelMenuPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btTransacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/analytics.png"))); // NOI18N
        btTransacoes.setBorder(null);
        btTransacoes.setContentAreaFilled(false);
        btTransacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTransacoesActionPerformed(evt);
            }
        });
        jPanelMenuPrincipal.add(btTransacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 2, -1, 110));

        btContas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/money-bag.png"))); // NOI18N
        btContas.setBorder(null);
        btContas.setContentAreaFilled(false);
        btContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContasActionPerformed(evt);
            }
        });
        jPanelMenuPrincipal.add(btContas, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 2, -1, 110));

        btCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/books.png"))); // NOI18N
        btCategoria.setBorder(null);
        btCategoria.setContentAreaFilled(false);
        btCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCategoriaActionPerformed(evt);
            }
        });
        jPanelMenuPrincipal.add(btCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 2, -1, 110));

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/open-door.png"))); // NOI18N
        btSair.setBorder(null);
        btSair.setContentAreaFilled(false);
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        jPanelMenuPrincipal.add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/onlinelogomaker-061817-1509-5100.png"))); // NOI18N
        jPanelMenuPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(767, 34, -1, -1));

        jLabel4.setText("Categorias");
        jPanelMenuPrincipal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 107, -1, -1));

        jLabel5.setText("Sair");
        jPanelMenuPrincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        jLabel6.setText("Contas");
        jPanelMenuPrincipal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 107, -1, -1));

        jLabel7.setText("Transações");
        jPanelMenuPrincipal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 107, -1, -1));

        jPanel1.add(jPanelMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 125));

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Icon made by Vectors Market from www.flaticon.com ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 650, 1100, -1));

        cxbSaldoAcumulado.setBackground(new java.awt.Color(255, 255, 255));
        cxbSaldoAcumulado.setText("Saldo acumulado");
        cxbSaldoAcumulado.setToolTipText("");
        cxbSaldoAcumulado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxbSaldoAcumuladoActionPerformed(evt);
            }
        });
        jPanel1.add(cxbSaldoAcumulado, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, -1, -1));

        jLabelTot.setFont(new java.awt.Font("Tahoma", 0, 86)); // NOI18N
        jLabelTot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTot.setText("00,00");
        jLabelTot.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabelTot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1100, 130));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);

        jTableTransac.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableTransac.setForeground(new java.awt.Color(102, 102, 102));
        jTableTransac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableTransac.setGridColor(new java.awt.Color(255, 255, 255));
        jTableTransac.setRowHeight(26);
        jTableTransac.setSelectionBackground(new java.awt.Color(50, 74, 94));
        jTableTransac.setShowHorizontalLines(false);
        jTableTransac.setShowVerticalLines(false);
        jScrollPane2.setViewportView(jTableTransac);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 620, 220));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(null);

        jTableLembrete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableLembrete.setForeground(new java.awt.Color(102, 102, 102));
        jTableLembrete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableLembrete.setGridColor(new java.awt.Color(255, 255, 255));
        jTableLembrete.setRowHeight(26);
        jTableLembrete.setSelectionBackground(new java.awt.Color(50, 74, 94));
        jTableLembrete.setShowHorizontalLines(false);
        jTableLembrete.setShowVerticalLines(false);
        jScrollPane3.setViewportView(jTableLembrete);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 400, 220));

        jLabel8.setText("Lembretes:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel9.setText("Maiores Transações:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, -1, -1));

        jMenu19.setText("Arquivo");

        btMenuTransacoes.setSelected(true);
        btMenuTransacoes.setText("Transações");
        btMenuTransacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTransacoesActionPerformed(evt);
            }
        });
        jMenu19.add(btMenuTransacoes);

        btMenuConta.setSelected(true);
        btMenuConta.setText("Conta");
        btMenuConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContasActionPerformed(evt);
            }
        });
        jMenu19.add(btMenuConta);

        btMenuCategoria.setSelected(true);
        btMenuCategoria.setText("Categoria");
        btMenuCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCategoriaActionPerformed(evt);
            }
        });
        jMenu19.add(btMenuCategoria);

        btMenuSair.setSelected(true);
        btMenuSair.setText("Sair");
        btMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        jMenu19.add(btMenuSair);

        jMenuBar3.add(jMenu19);

        jMenu28.setText("Relatório");

        jrbCategorias.setSelected(true);
        jrbCategorias.setText("Categorias");
        jrbCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCategoriasActionPerformed(evt);
            }
        });
        jMenu28.add(jrbCategorias);

        jrbConta.setSelected(true);
        jrbConta.setText("Conta");
        jrbConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbContaActionPerformed(evt);
            }
        });
        jMenu28.add(jrbConta);

        jrbTransacoes.setSelected(true);
        jrbTransacoes.setText("Transações");
        jrbTransacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTransacoesActionPerformed(evt);
            }
        });
        jMenu28.add(jrbTransacoes);

        jrbReceitas.setSelected(true);
        jrbReceitas.setText("Receitas");
        jrbReceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbReceitasActionPerformed(evt);
            }
        });
        jMenu28.add(jrbReceitas);

        jrbDespesas.setSelected(true);
        jrbDespesas.setText("Despesas");
        jrbDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDespesasActionPerformed(evt);
            }
        });
        jMenu28.add(jrbDespesas);

        jrbTransferencias.setSelected(true);
        jrbTransferencias.setText("Transferências");
        jrbTransferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTransferenciasActionPerformed(evt);
            }
        });
        jMenu28.add(jrbTransferencias);

        jMenu1.setText("Grafico Barras");

        jrbGrafReceita.setSelected(true);
        jrbGrafReceita.setText("Receitas");
        jrbGrafReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbGrafReceitaActionPerformed(evt);
            }
        });
        jMenu1.add(jrbGrafReceita);

        jrbGrafDespesas.setSelected(true);
        jrbGrafDespesas.setText("Despesas");
        jrbGrafDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbGrafDespesasActionPerformed(evt);
            }
        });
        jMenu1.add(jrbGrafDespesas);

        jMenu28.add(jMenu1);

        jMenu2.setText("Grafico Pizza");

        jrbPReceitas.setSelected(true);
        jrbPReceitas.setText("Receitas");
        jrbPReceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPReceitasActionPerformed(evt);
            }
        });
        jMenu2.add(jrbPReceitas);

        jrbPDespesas.setSelected(true);
        jrbPDespesas.setText("Despesas");
        jrbPDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPDespesasActionPerformed(evt);
            }
        });
        jMenu2.add(jrbPDespesas);

        jMenu28.add(jMenu2);

        jMenuBar3.add(jMenu28);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1100, 723));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void btTransacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTransacoesActionPerformed
        Transacoes telaTransacoes = Transacoes.getInstance();
        this.setVisible(false);
        telaTransacoes.setVisible(true);
        telaTransacoes.toFront();
    }//GEN-LAST:event_btTransacoesActionPerformed

    private void btContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContasActionPerformed
        Conta telaConta = Conta.getInstance();
        this.setVisible(false);
        telaConta.setVisible(true);
        telaConta.toFront();
    }//GEN-LAST:event_btContasActionPerformed

    private void jrbCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCategoriasActionPerformed
        try {
            conexao.conecta();
            conexao.executaSql("select * from V_CATEGORIAS;");
            JRResultSetDataSource jrRS = new JRResultSetDataSource(conexao.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("relatorios/Categorias.jasper", new HashMap(), jrRS);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setVisible(true);
            jv.toFront();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro =" + erro);
        }
    }//GEN-LAST:event_jrbCategoriasActionPerformed

    private void jrbTransacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTransacoesActionPerformed
        try {
            conexao.conecta();
            conexao.executaSql("SELECT DESCRCONTA Conta, DATA Data, MES_ANO Mes_Ano, VALOR Valor, TIPO Tipo,\n"
                    + "PAGO Pago, DESCRCAT Categoria, DESCRTRA Descricao from v_transacoes order by DATA desc;");
            JRResultSetDataSource jrRS = new JRResultSetDataSource(conexao.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("relatorios/Transacoes.jasper", new HashMap(), jrRS);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setVisible(true);
            jv.toFront();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro =" + erro);
        }
    }//GEN-LAST:event_jrbTransacoesActionPerformed

    private void jrbReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbReceitasActionPerformed
        try {
            conexao.conecta();
            conexao.executaSql("select DESCRCONTA as Conta, DATA AS Data, MES_ANO as Mes_Ano, \n"
                    + "VALOR as Valor, TIPO as Tipo, PAGO as Pago, DESCRCAT as Categoria, DESCRTRA as Descricao\n"
                    + "from V_TRANSACOES\n"
                    + "where TIPO = 'R'\n"
                    + "order by DATA desc;");
            JRResultSetDataSource jrRS = new JRResultSetDataSource(conexao.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("relatorios/Receitas.jasper", new HashMap(), jrRS);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setVisible(true);
            jv.toFront();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro =" + erro);
        }
    }//GEN-LAST:event_jrbReceitasActionPerformed

    private void jrbDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDespesasActionPerformed
        try {
            conexao.conecta();
            conexao.executaSql("select DESCRCONTA as Conta, DATA AS Data, MES_ANO as Mes_Ano, \n"
                    + "VALOR as Valor, TIPO as Tipo, PAGO as Pago, DESCRCAT as Categoria, DESCRTRA as Descricao\n"
                    + "from V_TRANSACOES\n"
                    + "where TIPO = 'D'\n"
                    + "order by DATA desc;");
            JRResultSetDataSource jrRS = new JRResultSetDataSource(conexao.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("relatorios/Despesas.jasper", new HashMap(), jrRS);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setVisible(true);
            jv.toFront();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro =" + erro);
        }
    }//GEN-LAST:event_jrbDespesasActionPerformed

    private void jrbTransferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTransferenciasActionPerformed
        try {
            conexao.conecta();
            conexao.executaSql("select DESCRCONTA as Conta, DATA AS Data, MES_ANO as Mes_Ano, \n"
                    + "VALOR as Valor, TIPO as Tipo, PAGO as Pago, DESCRCAT as Categoria, DESCRTRA as Descricao\n"
                    + "from V_TRANSACOES\n"
                    + "where TIPO = 'T'\n"
                    + "order by DATA desc;");
            JRResultSetDataSource jrRS = new JRResultSetDataSource(conexao.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("relatorios/Transferencias.jasper", new HashMap(), jrRS);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setVisible(true);
            jv.toFront();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro =" + erro);
        }
    }//GEN-LAST:event_jrbTransferenciasActionPerformed

    public void preencheTabelaLembretes() {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Descricao"};

        conexao.conecta();
        conexao.executaSql("select T.NOTA from TRANSACAO T where T.CODUSU = '" + usuario + "' and T.LEMBRETE >= CURRENT_DATE() and T.DATA <= CURRENT_DATE();");

        try {
            conexao.rs.beforeFirst();

            while (conexao.rs.next()) {
                dados.add(new Object[]{conexao.rs.getString("NOTA")});
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher Tabela de Lembretes!" + ex);
        }
        if (dados.isEmpty()) {
            dados.add(new Object[]{' '});
        }

        MTabela tabela = new MTabela(dados, colunas);

        jTableLembrete.setModel(tabela);

        jTableLembrete.getColumnModel().getColumn(0).setPreferredWidth(400);
        jTableLembrete.getColumnModel().getColumn(0).setResizable(false);

        jTableLembrete.getTableHeader().setReorderingAllowed(false);
        jTableLembrete.setAutoResizeMode(jTableLembrete.AUTO_RESIZE_ALL_COLUMNS);

        jTableLembrete.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        conexao.desconecta();
        jTableLembrete.setColumnSelectionInterval(0, 0);
        jTableLembrete.setRowSelectionInterval(0, 0);
    }

    public void preencheTabelaTransac() {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Descricao", "Valor"};

        conexao.conecta();
        conexao.executaSql("select T.DESCRTRA, T.VALOR from TRANSACAO T where T.CODUSU = '" + usuario + "' and MONTH(T.DATA) = MONTH(CURRENT_DATE()) and YEAR(T.DATA) = YEAR(CURRENT_DATE()) ORDER BY T.VALOR desc limit 7;");

        try {
            conexao.rs.beforeFirst();

            while (conexao.rs.next()) {
                dados.add(new Object[]{conexao.rs.getString("DESCRTRA"), conexao.rs.getFloat("VALOR")});
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher Tabela de Transações!" + ex);
        }
        if (dados.isEmpty()) {
            dados.add(new Object[]{' '});
        }

        MTabela tabela = new MTabela(dados, colunas);

        jTableTransac.setModel(tabela);

        jTableTransac.getColumnModel().getColumn(0).setPreferredWidth(470);
        jTableTransac.getColumnModel().getColumn(0).setResizable(false);
        jTableTransac.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTableTransac.getColumnModel().getColumn(1).setResizable(false);
        jTableTransac.getTableHeader().setReorderingAllowed(false);
        jTableTransac.setAutoResizeMode(jTableTransac.AUTO_RESIZE_OFF);

        jTableTransac.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        conexao.desconecta();
        jTableTransac.setColumnSelectionInterval(0, 0);
        jTableTransac.setRowSelectionInterval(0, 0);
    }

    public void totalGasto() {
        conexao.conecta();
        if (cxbSaldoAcumulado.isSelected()) {
            conexao.executaSql("select format(sum(C.SALDOCON),2,'de_DE') VALOR from CONTA C where C.CODUSU = '" + usuario + "';");
        } else {
            conexao.executaSql("select format(sum(dados.VALOR),2,'de_DE') VALOR\n"
                    + "from(\n"
                    + "select sum(T.VALOR)*(-1) VALOR from TRANSACAO T where T.TIPO = 'D' and T.CODUSU = '" + usuario + "' and MONTH(T.DATA) = MONTH(CURRENT_DATE()) and YEAR(T.DATA) = YEAR(CURRENT_DATE())\n"
                    + "union all\n"
                    + "select sum(T.VALOR) VALOR from TRANSACAO T where T.TIPO = 'D' and T.CODUSU = '" + usuario + "' and MONTH(T.DATA) = MONTH(CURRENT_DATE()) and YEAR(T.DATA) = YEAR(CURRENT_DATE())\n"
                    + ") dados");
        }
        try {
            conexao.rs.first();
            jLabelTot.setText(conexao.rs.getString("VALOR"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher Tabela de Lembretes!" + ex);
        }
    }

    private void btCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCategoriaActionPerformed
        Categoria telaCategoria = Categoria.getInstance();
        this.setVisible(false);
        telaCategoria.setVisible(true);
        telaCategoria.toFront();
    }//GEN-LAST:event_btCategoriaActionPerformed

    private void cxbSaldoAcumuladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxbSaldoAcumuladoActionPerformed
        totalGasto();
    }//GEN-LAST:event_cxbSaldoAcumuladoActionPerformed

    private void jrbContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbContaActionPerformed
        try {
            conexao.conecta();
            conexao.executaSql("select CODCON, DESCRCON, ATIVO from V_CONTAS;");
            JRResultSetDataSource jrRS = new JRResultSetDataSource(conexao.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("relatorios/Contas.jasper", new HashMap(), jrRS);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setVisible(true);
            jv.toFront();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro =" + erro);
        }
    }//GEN-LAST:event_jrbContaActionPerformed

    private void jrbGrafReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbGrafReceitaActionPerformed
        try {
            conexao.conecta();
            conexao.executaSql("select DESCRCAT as descrcat, sum(VALOR) AS valor\n"
                    + "from V_TRANSACOES\n"
                    + "where TIPO = 'R'\n"
                    + "group by DESCRCAT, DESCRCONTA;");
            JRResultSetDataSource jrRS = new JRResultSetDataSource(conexao.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("relatorios/Grafico_Barras_Receitas.jasper", new HashMap(), jrRS);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setVisible(true);
            jv.toFront();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro =" + erro);
        }
    }//GEN-LAST:event_jrbGrafReceitaActionPerformed

    private void jrbGrafDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbGrafDespesasActionPerformed
        try {
            conexao.conecta();
            conexao.executaSql("select DESCRCAT as descrcat, sum(VALOR) AS valor\n"
                    + "from V_TRANSACOES\n"
                    + "where TIPO = 'D'\n"
                    + "group by DESCRCAT, DESCRCONTA;");
            JRResultSetDataSource jrRS = new JRResultSetDataSource(conexao.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("relatorios/Grafico_Barras_Despesas.jasper", new HashMap(), jrRS);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setVisible(true);
            jv.toFront();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro =" + erro);
        }
    }//GEN-LAST:event_jrbGrafDespesasActionPerformed

    private void jrbPReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPReceitasActionPerformed
        try {
            conexao.conecta();
            conexao.executaSql("select DESCRCAT as descrcat, sum(VALOR) AS valor\n"
                    + "from V_TRANSACOES\n"
                    + "where TIPO = 'R'\n"
                    + "group by DESCRCAT, DESCRCONTA;");
            JRResultSetDataSource jrRS = new JRResultSetDataSource(conexao.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("relatorios/Grafico_pie_Receitas.jasper", new HashMap(), jrRS);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setVisible(true);
            jv.toFront();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro =" + erro);
        }
    }//GEN-LAST:event_jrbPReceitasActionPerformed

    private void jrbPDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPDespesasActionPerformed
                try {
            conexao.conecta();
            conexao.executaSql("select DESCRCAT as descrcat, sum(VALOR)*(-1) AS valor\n"
                    + "from V_TRANSACOES\n"
                    + "where TIPO = 'D'\n"
                    + "group by DESCRCAT, DESCRCONTA;");
            JRResultSetDataSource jrRS = new JRResultSetDataSource(conexao.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("relatorios/Grafico_pie_Despesas.jasper", new HashMap(), jrRS);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setVisible(true);
            jv.toFront();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro =" + erro);
        }
    }//GEN-LAST:event_jrbPDespesasActionPerformed

    public static Principal getInstance() { // MÉTODO QUE VERIFICA SE A INSTANCIA JÁ ESTÁ CRIADA (SINGLETON)
        if (instancia == null) {
            instancia = new Principal();
        }
        return instancia;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCategoria;
    private javax.swing.JButton btContas;
    private javax.swing.JRadioButtonMenuItem btMenuCategoria;
    private javax.swing.JRadioButtonMenuItem btMenuConta;
    private javax.swing.JRadioButtonMenuItem btMenuSair;
    private javax.swing.JRadioButtonMenuItem btMenuTransacoes;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btTransacoes;
    private javax.swing.JCheckBox cxbSaldoAcumulado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTot;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu28;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMenuPrincipal;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableLembrete;
    private javax.swing.JTable jTableTransac;
    private javax.swing.JRadioButtonMenuItem jrbCategorias;
    private javax.swing.JRadioButtonMenuItem jrbConta;
    private javax.swing.JRadioButtonMenuItem jrbDespesas;
    private javax.swing.JRadioButtonMenuItem jrbGrafDespesas;
    private javax.swing.JRadioButtonMenuItem jrbGrafReceita;
    private javax.swing.JRadioButtonMenuItem jrbPDespesas;
    private javax.swing.JRadioButtonMenuItem jrbPReceitas;
    private javax.swing.JRadioButtonMenuItem jrbReceitas;
    private javax.swing.JRadioButtonMenuItem jrbTransacoes;
    private javax.swing.JRadioButtonMenuItem jrbTransferencias;
    // End of variables declaration//GEN-END:variables
}
